### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by floscher**
This PR lets Travis CI upload the translatable strings to Transifex, where these can be translated. Later you could then add the translations to the plugin to make it multilingual.

To enable this, you'll need an [API token for Transifex](https://www.transifex.com/user/settings/api/). Add that as environment variable `$TRANSIFEX_TOKEN` to the [Travis CI settings](https://travis-ci.org/matsim-org/josm-matsim-plugin/settings).
You'd also have to become a member of the JOSM team to be able to upload source strings.

If all that is set up, the strings should automatically be uploaded to Transifex, every time somebody pushes to the master branch.

### CODE REVIEW

**Comment by floscher** [comment]
Would you be interested in adding translations for other languages to the plugin?

**Comment by floscher** [comment]
Great :+1: I added you to the JOSM team at Transifex, so you have the rights to push translations with your API key.

**Comment by floscher** [comment]
Ah, I see: Above I used the notation how the variable is accessed in bash `$TRANSIFEX_TOKEN`, the variable name has to be without the dollar sign: `TRANSIFEX_TOKEN`.

https://travis-ci.org/matsim-org/josm-matsim-plugin/jobs/346840337#L424-L428

Then it should work :crossed_fingers:

**Comment by nkuehnel** [comment]
Aah! Thanks a lot die your effort :)

**Pull request merged**
