### PR TITLE
Add missing JavaFX Plugin dependency

### PR DESCRIPTION
**Pull request by don-vip**

### CODE REVIEW

**Comment by don-vip** [comment]
@floscher The JOSM Gradle plugin needs to be updated to resolve virtual plugins introduced in [14384](https://josm.openstreetmap.de/changeset/14384/josm).

**Comment by floscher** [comment]
@don-vip Ok, I'll add resolution of virtual plugins (tracked [as ticket #8](https://gitlab.com/floscher/gradle-josm-plugin/issues/8)).

**Comment by nkuehnel** [comment]
Thank you both very much, keep me posted!

**Comment by floscher** [comment]
Starting with the next release `v0.6.1` the `gradle-josm-plugin` will resolve the virtual plugins, I added the functionality to the project already. The release will be made probably in the coming week.

**Comment by don-vip** [comment]
@floscher the plugin is not found:

```
Plugin [id: 'org.openstreetmap.josm', version: '0.6.1'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.openstreetmap.josm:org.openstreetmap.josm.gradle.plugin:0.6.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

**Comment by floscher** [comment]
@don-vip I didn't make the release yet, I'll comment here again when it's ready, it won't take long anymore.

**Comment by floscher** [comment]
Finally the version `0.6.1` of the gradle-josm-plugin is released: https://gitlab.com/floscher/gradle-josm-plugin/releases :tada: 

You can now use it, when updating to this version, you should update the Gradle wrapper also to a Gradle version of at least 5.1 (5.2.1 would be the currently latest version). Other than that, there should be no other changes needed.

**Comment by don-vip** [comment]
@nkuehnel I don't understand the compilation errors on Travis.

**Comment by nkuehnel** [comment]
working on it!

**Comment by nkuehnel** [comment]
will fix it on master branch, thanks again!

**Pull request merged**
